### ISSUE TITLE
feature - is it possible to add a custom domain?

### ISSUE THREAD

**Issue by rokimiftah** [mikhailsdv/deta-black-hole#2]
Is it possible to add a custom domain? or pointing the CNAME to another domain? if possible this is an alternative to B2 Backblaze.

**Comment by mikhailsdv** [comment]
Maybe in the future it will be possible to add custom domain for Deta app, but as i know it's not possible at the moment. I think it's better to ask the Deta team. Actually, you can host this app on any domain because it's just `create-react-app` application. Set your Deta project key in the `.env` file of backend instance and host the project in any cloud with nodejs support.
